### ISSUE TITLE
test ( Infinite money glitch) not real don't worry

### ISSUE THREAD

**Issue by Mlgboy22** [Team-Tiny-TT/bug-reports#3]
**Describe the issue:** - a bug that lets you get "Infinite money" if you stand in the left corner of the map.

**Steps to reproduce:**  
1. Start the game on hard mode.
2.Place a tower in the close mid area.
3. See were your were your enemies coming out from and go to the left side of that.
4. Then go to the corner.
5. And remove the tower then you will get "Infinite money".

**Impact:** - **High**, Players can cheat the game and ruin the leaderboard!
**Date First Experienced:** -*12/3/2021 2:58:42 (-06:00).*
**Date Last Experienced:** -*12/3/2021 2:59:32 (-06:00).*
**Additional details / images:** N/A

**Comment by Mlgboy22** [comment]
please give me full feedback and criticism

**Comment by IdentityHozan** [comment]
LGTM! Overall, it's good but workaround with your formatting and whatnot. Your steps to reproduce are funky. For real-time issues, make sure the bug is descriptive, clear, and concise.
