### ISSUE TITLE
yh

### ISSUE THREAD

**Issue by IcedMellow** [Team-Tiny-TT/bug-reports#4]
**Describe the issue:** - *A clear and detailed description, explain what you expect, and what happens instead.* Banana

**Steps to reproduce:**  - *Information can be found in #bug-reports* Banana

**Impact:** - *High, Medium, or Small. How heavily does this bug impact the game?* A
**Date First Experienced:** -*When was the first time you encountered the bug? Include the date and time (including timezone).* B
**Date Last Experienced:** -*When was the last time you encountered the bug? Include the date and time (including timezone).* C
**Additional details / images:** -*Include visuals to demonstrate the problem.* D

**Comment by IdentityHozan** [comment]
LGTM!
