### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by AmISomeoneAtAll** [Team-Tiny-TT/bug-reports#6]
Describe the issue: There's a GUI bug in which after you close the matchmaking menu you can't see the GUI buttons but you can only open the matchmaking menu by pressing "N"

Steps to reproduce:
1. Open the matchmaking menu by clicking on it or pressing M.
2. Close the matchmaking menu.

Impact: Medium/Low
Date First Experienced: 2021-12-02 15:20 
Date Last Experienced: 2021-12-03 15:20
Additional details / images: 

https://user-images.githubusercontent.com/95508157/155797607-5174cf60-c57e-43b9-9481-08dc34b7c22b.mp4

**Comment by IdentityHozan** [comment]
Issue has been fixed in the latest push.
