### ISSUE TITLE
GUI/UI bug 

### ISSUE THREAD

**Issue by sansbutgaming** [Team-Tiny-TT/bug-reports#8]
When resetting, everything on the left side of the screen (Settings, Shop, Matchmaking, etc) disappears. 
Rejoining fixes it though, just seems like a bit of an issue.
![RobloxScreenShot20220226_133313970](https://user-images.githubusercontent.com/100488055/155855050-a33f4831-9823-4b01-aff4-b7dede417fd9.png)
![RobloxScreenShot20220226_133533760 (2)](https://user-images.githubusercontent.com/100488055/155855102-7207d383-2283-45e4-b4b9-a0814200545b.png)

**Comment by IdentityHozan** [comment]
Issue has been fixed with the latest push
